[
  "modern e-commerce website with shopping cart",
  "corporate website with clean design",
  "fitness tracking mobile app interface",
  "mobile banking application screenshot",
  "cloud server infrastructure diagram",
  "hybrid cloud architecture visualization",
  "business analytics dashboard with charts",
  "data visualization with colorful graphs",
  "content management system backend",
  "travel app with map integration",
  "database optimization performance metrics",
  "machine learning model visualization",
  "responsive web design on multiple devices",
  "mobile app development workflow",
  "cloud migration process infographic",
  "AI integration in business processes",
  "cybersecurity threat analysis dashboard",
  "data center server room overview"
]